### ISSUE TITLE
建议添加接口直接读取修复webm文件

### ISSUE THREAD

**Issue by DogeVenci** [StaZhu/fix-webm-meta#1]
mediaRecorder.start() 使用timeslice后在ondataavailable里面用 fixWebmMetaInfo有问题。
建议直接读取已经完整生成的webm文件后修改文件头

**Comment by StaZhu** [comment]
具体是什么问题，辛苦贴一下代码，理论上现在就是直接读取webm修复文件头

**Comment by StaZhu** [comment]
doc已更新

**Comment by DogeVenci** [comment]
用默认的方法长时间录制依旧会占用大量内存还有大小限制，我想的最好办法是在ondataavailable里面直接将data写入外部文件，stop后在修复整个文件 @StaZhu

**Comment by StaZhu** [comment]
现在不就是么 @DogeVenci

**Comment by DogeVenci** [comment]
@StaZhu 是直接用fs.appendFileSync而不是Blob

**Comment by StaZhu** [comment]
看readme

**Comment by StaZhu** [comment]
直接修blob @DogeVenci

**Comment by DogeVenci** [comment]
@StaZhu 我知道直接修改blob可以，是想加个接口直接修改现成的文件
参考ts-ebml的这个方法
[try-to-convert-a-mediarecorder-webm-to-seekable-webm](https://github.com/legokichi/ts-ebml#try-to-convert-a-mediarecorder-webm-to-seekable-webm)
