### ISSUE TITLE
Uncaught (in promise) Error: No schema entry found for TimecodeScale

### ISSUE THREAD

**Issue by zxxwslq** [StaZhu/fix-webm-meta#6]
报错了

**Comment by StaZhu** [comment]
已知问题 欢迎提pr修复

**Comment by zxxwslq** [comment]
大神，能否发个新版本？

**Comment by StaZhu** [comment]
> 大神，能否发个新版本？

新版依然有bug，目前貌似没啥太好的解决办法，你可以看下最新合入的pr下面那个哥们的评论

**Comment by StaZhu** [comment]
https://github.com/StaZhu/fix-webm-meta/pull/5#issuecomment-1106482903

**Comment by maxirozay** [comment]
Your dist files and src files are different and if you change `dist/matroska-schema.js` => `name: 'TimecodeScale',` by `name: "TimestampScale",
cppname: "TimecodeScale",` as it is in `src/matroska-schema.ts` the error disappear. Maybe you just need to publish a new build to fix this error.

**Comment by StaZhu** [comment]
Thanks for the remind, just published a new version 1.0.8

**Comment by StaZhu** [comment]
> Your dist files and src files are different and if you change `dist/matroska-schema.js` => `name: 'TimecodeScale',` by `name: "TimestampScale", cppname: "TimecodeScale",` as it is in `src/matroska-schema.ts` the error disappear. Maybe you just need to publish a new build to fix this error.

But as far as know, their maybe a another issue as mentioned in the last comment of this pr https://github.com/StaZhu/fix-webm-meta/pull/5#issuecomment-1106482903
